// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrvT8PTFekqm4IUQDw9gYngoCJqHikXY',
    appId: '1:972318516893:android:57d25caaa9edac2aa4d674',
    messagingSenderId: '972318516893',
    projectId: 'uas-21312128',
    authDomain: 'uas-21312128.firebaseapp.com',
    storageBucket: 'uas-21312128.appspot.com',
    measurementId: 'G-T3H6J89D2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSr23sB_WZxDuLZ77IfKUzGSgcIvQCoFQ',
    appId: '1:972318516893:android:57d25caaa9edac2aa4d674',
    messagingSenderId: '972318516893',
    projectId: 'uas-21312128',
    storageBucket: 'uas-21312128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLw_Y1yPOJriq8AO4Egn_yQqu3rdVz3E',
    appId: '1:972318516893:ios:da735bf566e0fd58a4d674',
    messagingSenderId: '972318516893',
    projectId: 'uas-21312128',
    storageBucket: 'uas-21312128.appspot.com',
    iosBundleId: 'com.teknokrat.uas21312128',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLw_Y1yPOJriq8AO4Egn_yQqu3rdVz3E',
    appId: '1:972318516893:ios:3d1dcb1a4ea50acfa4d674',
    messagingSenderId: '972318516893',
    projectId: 'uas-21312128',
    storageBucket: 'uas-21312128.appspot.com',
    iosBundleId: 'com.teknokrat.uas21312128.RunnerTests',
  );
}
